import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>OttoService</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='sm:max-w-[40vw] ml-auto mr-auto'>
        <Navbar />
        <img src='https://res.cloudinary.com/dzrthkexn/image/upload/v1683888742/logo-black_lrasbr.png' className='w-full h-auto' />
      </div>
    </>
  )
}
